version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: artisan_db_container
    environment:
      - POSTGRES_DB=${DB_NAME:-artisan_db}
      - POSTGRES_USER=${DB_USER:-artisan_admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-artisan_secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    container_name: artisan_api_container
    # ATENÇÃO: Aqui mudamos de artisan para seu projeto específico
    command: gunicorn artisan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-artisan_db}
      - DB_USER=${DB_USER:-artisan_admin}
      - DB_PASSWORD=${DB_PASSWORD:-artisan_secret}
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
    restart: always

volumes:
  postgres_data: